#!/bin/sh
(
echo "10" ; sleep 1
echo "# Smelling the roses..."
echo "20" ; sleep 1 
echo "# They smell sooo good"
echo "50" ; sleep 1
echo "lol" ; sleep 1 
echo "75" ; sleep 1 
echo "# Formatting done." ;  sleep 1 
echo "100" ; sleep 1 
) | 
zenity --progress \
 --title="Sunshine and rainbows Setup Wizard" \
 --text="Starting...." \
 --percentage=0

if [ "$?" = -1 ] ; then
            zenity --error \
              --text=":("
fi 

